#pragma once

#define SAMPLING_DELAY_MILLIS 20
#define LED_UPDATE_DELAY_MILLIS 100
#define ADC_POLL_TIMEOUT_MILLIS 1

#define SMA_BUFFER_SIZE 16

#define LED_GPIO_PORT GPIOA
#define LED_GPIO_PIN GPIO_PIN_5

#define SMA_FILTER_SWITCH_THRESHOLD 2500
#define SMA_FILTER_HYSTERESIS_RANGE 50

#define CALIBRATED_LDR_MIN 60
#define CALIBRATED_LDR_MAX 4020
