#pragma once

#define BUTTON_DEBOUNCE_DELAY_MILLIS 500

#define SEND_MESSAGE ('x')
#define SEND_MESSAGE_LENGTH 1
#define SEND_TIMEOUT_MILLIS 10

#define RECEIVE_MESSAGE_LENGTH 1
#define RECEIVE_TIMEOUT_MILLIS 1

#define LOCAL_LED_PORT GPIOA
#define LOCAL_LED_PIN GPIO_PIN_8
#define REMOTE_LED_PORT GPIOA
#define REMOTE_LED_PIN GPIO_PIN_5
