[tools]
# rust = "latest"

[env]
DEFMT_LOG = "trace"
INIT_DATE_TIME = "2015-09-18T23:56:04"
CLEAR_MEMORY = false
CREATE_DEMO_DATA = false
PRINT_REPORT = true
COLLECT_NEW_DATA = false
SEND_DEMO_BATCHES_NUM = 1
SHOULD_SEND_MEASUREMENTS = false

[tasks.run]
run = "cargo run"

[tasks.build]
alias = "b"
run = "cargo build"

[tasks.test]
alias = "t"
run = "cargo test"

[tasks.flash-monitor-stm]
alias = "fms"
run = "(cd stm32-target && cargo run)"

[tasks.flash-monitor-esp]
alias = "fme"
run = "(cd esp32-target && cargo run)"

