[tools]
# rust = "latest"

[env]
DEFMT_LOG = "trace"

[tasks.run]
run = "cargo run"

[tasks.build]
alias = "b"
run = "cargo build"

[tasks.build-release]
run = "cargo build --release"

[tasks.flash-monitor]
depends = "build"
alias = "fm"
run = "probe-rs run --chip STM32F446RE target/thumbv7em-none-eabihf/debug/blinky_esp_rust"

[tasks.flash-monitor-release]
alias = "fmr"
depends = "build-release"
run = "probe-rs run --chip STM32F446RE target/thumbv7em-none-eabihf/release/blinky_esp_rust"
